### ISSUE TITLE
Move mandatory attribute of XML element from being mandatory element of object 

### ISSUE THREAD

**Issue by opoudjis** [nsip/specgen_input#40]
> SIF_RefObject is defined as required field under SchoolInfo object, but as per the example that is part of "OtherLEA" object and not in root level for SchoolInfo. Specification seems to be wrong.

Me: This is indeed an error in the JSON Schema generation: @SIF_RefObject is mandatory within the object it is an attribute of, not within the host object. 

This is the JSON Schema generation reading specgen naively, and the initial implementation won’t have paid attention to it as it was done for NZ and not using attributes anyway. This should have been fixed for the rendering of the JSON in payload.

**Comment by opoudjis** [comment]
@joerghuber Wait until I investigate this a bit more.

**Comment by opoudjis** [comment]
I actually think the real solution to this is either to change the specgen source, so that 

IdRef + SIF_RefObject

becomes a new type (and that's the usual circumstance), or else some quite convoluted parsing of the items in a sequence, to generate new ad hoc types. 

Note also that there is a lot of ad hoc enumerating of  SIF_RefObject values. it is not tenable to transport this validation if the Element + Attribute combination turns into a new type. But restrictions of Object.Element.SIF_RefObject values for that full path are beyond JSON Schema, and should be.

I think this particular enum restriction is too hard to transfer to JSON Schema, for not enough payoff. Making IdRef + SIF_RefObject etc a new type is the best outcome...

**Comment by 4pins** [comment]
@opoudjis This seems like a wonderful idea!

**Comment by opoudjis** [comment]
Actually, I've tweaked this, and I'm going to see if I can solve it with less effort.

I'm now going to try doing the following:

* The major class of ad hoc attributes are SIF_RefObject. I am going to detect these during compilation, and on the fly change the type of the parent element to a new type, TypedIdRefType, which I'll define in common types. I will do away with all type validation. That way, the major class of ad hoc attributes can be left alone.
* I will find the remaining ad hoc attributes in the spec (there are not that many), and redefine them as standalone types.

This will reduce the transition effort significantly. Going to try it out today.

**Comment by opoudjis** [comment]
If I can trust the Redocly error log as an indicator:

SIF_Refobject instances, that will be taken care of by TypedIdRefType automatically, fingers crossed:

* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `OtherLEA` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ManagingSchool` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `InvoicedEntity` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `BilledEntity` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `PersonRefId` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ParentObjectRefId` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ResourceRefId` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `LocationRefId` property type must be string.: 32
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `SIF_RefId` property type must be string.: 32
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'SIF_RefObject'.: 65

Other attributes, that need to be moved into new types:

* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Location` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Duration` property type must be integer.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `LearningResource` property must have required property 'ReferenceType'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Activity` property must have required property 'EvaluationType'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `AggregateStatisticInfo` property must have required property 'Type'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'EvaluationType'.: 3
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'ReferenceType'.: 3
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ActivityTime` property must have required property 'Units'.: 5
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `IdentityAssertions` property must have required property 'SchemaName'.: 5
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `CalculationRule` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `PersonPicture` property must have required property 'Type'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `PictureSource` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `OtherCodeList` property must have required property 'Codeset'.: 50

For those of you with long memories: this is a (half-way) Venetian Blinds refactoring of Element + Attribute pairs in the spec, that in retrospect should have been done along with all the other Venetian Blinds out of Russian Doll refactoring that was done on Specgen XML years ago. By leaving the IdRef + Type (and their idiosyncratic enums) alone in the XML, we're substantially removing the number of types we end up having to shuffle, and we're not losing the idiosyncratic Object-specific enum validations.

**Comment by opoudjis** [comment]
Will ignore attributes as potential required fields unless they are attributes of the root element being described. As an approximation of this: /Item[2][Attribute] is a root element attribute. /Item[3][Attribute] is if  /Item[2][Attribute].  /Item[4][Attribute] is if  /Item[2][Attribute] and  /Item[3][Attribute].

**Comment by opoudjis** [comment]
Because the name of the attribute is part of the definition of an element type, only elements with attribute SIF_RefObject can be moved to TypedIdRefType . If another attribute name has been used, that will need to be factored out as a new type.

**Comment by opoudjis** [comment]
Needing to add  ` ref="CommonTypes"` to Generic-CommonTypes.xml, for their types to be processed correctly.

**Comment by opoudjis** [comment]
In fact all these additions of attributes to existing types need to be treated as extensions (`complex="extension"`).

**Comment by opoudjis** [comment]
No, they can't, because this is a string turned into an object

**Comment by opoudjis** [comment]
Need to factor out in specgen:

/CommonElement consisting of List, Element, Attribute => /CommonElement consisting of List, /CommonElement consisting of Element, Attribute : e.g. IdentityAssertionsType
