### ISSUE TITLE
Courtesy default dummy security policy

### ISSUE THREAD

**Issue by opoudjis** [nsip/specgen_input#46]
Do we define a default, dummy security policy in the OpenAPI at the root of the document? We don't have to, but we could include Basic HTTP SIF as a courtesy  to novices:

`Error :: security-defined rule :: Every operation should have security defined on it or on the root level.:`

800 of the 11398 errors generated.

**Comment by opoudjis** [comment]
Put in basic authentication, as a starting point security policy.

**Comment by joerghuber** [comment]
Added SIF_HMACSHA256 and Bearer as additional security schemas.
