### ISSUE TITLE
Document OpenAPI and JSON Schema versions publicly

### ISSUE THREAD

**Issue by opoudjis** [nsip/specgen_input#51]
Someone writes a page on a4ldocumentation with our agreed OpenAPI standards: which version of OpenAPI we are standardising on (3.0.3), a statement that we may consider 2.0 or 3.1 as need arises.

**Comment by joerghuber** [comment]
Added details about version of Open API and when to use which: https://a4ldocumentation.atlassian.net/wiki/spaces/ARCHITECTU/pages/20119553/SIF+Open+API
