### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by opoudjis** [nsip/specgen_input#58]
As of 19:00, 2022-12-19:

Now validating correctly.

Status as of right now:

1794 errors, 19468 warnings

Commenting out all Goessner examples:

````
\r(\s+)(create|update)Goessner:\r
\r#\1\2Goessner:\r#
````

1794 errors, 5682 warnings

Errors:
* Property `create/updateObject` is not expected here: https://github.com/nsip/specgen_input_au/issues/50: 960
* Every operation should have security defined on it or on the root level: https://github.com/nsip/specgen_input_au/issues/46: 800
* Property `name` is not expected here: https://github.com/nsip/specgen_input_au/issues/45: 25
* Expected type `array` but got `null`: https://github.com/nsip/specgen_input_au/issues/54: 4
* Property `in` is not expected here:  https://github.com/nsip/specgen_input_au/issues/45: 25
* Property `host` is not expected here: https://github.com/nsip/specgen_input_au/issues/55: 1
* Property `basePath` is not expected here: https://github.com/nsip/specgen_input_au/issues/55: 1
* Servers must be present:  https://github.com/nsip/specgen_input_au/issues/55: 1

Warnings:
* Warning Goessner misvalidation: https://github.com/nsip/specgen_input_au/issues/47: 14336

Excluding Goessner examples, which generate a lot of undetected errors

* Failing to process alias types: https://github.com/nsip/specgen_input_au/issues/53: 3612
* Example value must conform to the schema: must match exactly one schema in oneOf: (_grammar issues not yet resolved_): 571

Other, include https://github.com/nsip/specgen_input_au/issues/40, https://github.com/nsip/specgen_input_au/issues/53
 
* Warning info-license rule :: Info object should contain `license` field.: 1
* Warning no-unused-components rule :: Component: "schemaDefinitions" is never used.: 1
* Warning no-unused-components rule :: Component: "responsePayloads" is never used.: 1
* Warning no-unused-components rule :: Component: "requestPayloads" is never used.: 1
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Activity` property must have required property 'EvaluationType'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `AggregateStatisticInfo` property must have required property 'Type'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `PersonPicture` property must have required property 'Type'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `BilledEntity` property type must be string.: 3
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `OtherLEA` property type must be string.: 3
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'EvaluationType'.: 3
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Location` property type must be string.: 3
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must NOT have unevaluated properties {Data Model}.: 4
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `IdentityAssertions` property must have required property 'SchemaName'.: 5
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ActivityTime` property must have required property 'Units'.: 5
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'Type'.: 6
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `CalculationRule` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `PersonRefId` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `InvoicedEntity` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ParentObjectRefId` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `IdentityAssertion` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Duration` property type must be integer.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ManagingSchool` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ResourceRefId` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property type must be string.: 11
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `code` property type must be integer.: 13
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `LocationRefId` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `SIF_RefId` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: {Data Model} property must NOT have unevaluated properties {Data Model}.: 20
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `OtherCodeList` property must have required property 'Codeset'.: 45
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'SIF_RefObject'.: 60
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `OtherCode` property type must be string.: 75
* Warning XML misvalidation :: : 122
* Example validation errored: required value must be ["array"]: https://github.com/nsip/specgen_input_au/issues/38: 126
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: must NOT have unevaluated properties {Data Model}.: 141
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: {Infrastructure} property must NOT have unevaluated properties {Infrastructure}.: 143
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: must NOT have unevaluated properties {Infrastructure}.: 145

**Comment by opoudjis** [comment]
11:30 PM, 2022-12-19

1790 errors, 30728 warnings

Errors:
* Property `create/updateObject` is not expected here: https://github.com/nsip/specgen_input_au/issues/50: 960
* Every operation should have security defined on it or on the root level: https://github.com/nsip/specgen_input_au/issues/46: 800
* Property `name` is not expected here: https://github.com/nsip/specgen_input_au/issues/45: 25
* ~Expected type `array` but got `null`: https://github.com/nsip/specgen_input_au/issues/54: 4~
* Property `in` is not expected here:  https://github.com/nsip/specgen_input_au/issues/45: 2
* Property `host` is not expected here: https://github.com/nsip/specgen_input_au/issues/55: 1
* Property `basePath` is not expected here: https://github.com/nsip/specgen_input_au/issues/55: 1
* Servers must be present:  https://github.com/nsip/specgen_input_au/issues/55: 1

Warnings:
* Warning Goessner misvalidation: https://github.com/nsip/specgen_input_au/issues/47: 24806

Excluding Goessner examples, which generate a lot of undetected errors

* Failing to process alias types: https://github.com/nsip/specgen_input_au/issues/53: 4282
* Example value must conform to the schema: must match exactly one schema in oneOf: (_grammar issues not yet resolved_): 642
* ~Example validation errored: required value must be ["array"]: https://github.com/nsip/specgen_input_au/issues/38: 126~

Other, include https://github.com/nsip/specgen_input_au/issues/40, https://github.com/nsip/specgen_input_au/issues/53
 
* Warning no-unused-components rule :: Component: "schemaDefinitions" is never used.: 1
* Warning no-unused-components rule :: Component: "responsePayloads" is never used.: 1
* Warning no-unused-components rule :: Component: "requestPayloads" is never used.: 1
* Warning info-license rule :: Info object should contain `license` field.: 1
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `LearningResource` property must have required property 'ReferenceType'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `PersonPicture` property must have required property 'Type'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `AggregateStatisticInfo` property must have required property 'Type'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Activity` property must have required property 'EvaluationType'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'ReferenceType'.: 3
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'EvaluationType'.: 3
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must NOT have unevaluated properties {Data Model}.: 4
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `IdentityAssertions` property must have required property 'SchemaName'.: 5
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `DepartureSchool` property must have required property 'City'.: 5
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ActivityTime` property must have required property 'Units'.: 5
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'Type'.: 6
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ParentObjectRefId` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `CalculationRule` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `IdentityAssertion` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ManagingSchool` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Location` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `OtherLEA` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `BilledEntity` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `InvoicedEntity` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ResourceRefId` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `PersonRefId` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Duration` property type must be integer.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'City'.: 10
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `code` property type must be integer.: 13
* Warning XML misvalidation :: : 14
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `DomainScore` property must have required property 'PlausibleScaledValueList'.: 15
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `DomainScore` property must have required property 'ScaledScoreStandardError'.: 15
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `DomainScore` property must have required property 'ScaledScoreLogitValue'.: 15
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `DomainScore` property must have required property 'ScaledScoreLogitStandardError'.: 15
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `DomainScore` property must have required property 'RawScore'.: 15
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `SIF_RefId` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `LocationRefId` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: {Data Model} property must NOT have unevaluated properties {Data Model}.: 20
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `OtherCodeList` property must have required property 'Codeset'.: 50
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'SIF_RefObject'.: 75
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `OtherCode` property type must be string.: 80
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: must NOT have unevaluated properties {Data Model}.: 158
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: {Infrastructure} property must NOT have unevaluated properties {Infrastructure}.: 161
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: must NOT have unevaluated properties {Infrastructure}.: 163

**Comment by opoudjis** [comment]
> Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: DomainScore property must have required property 'PlausibleScaledValueList'.: 15
> Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: DomainScore property must have required property 'ScaledScoreStandardError'.: 15
> Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: DomainScore property must have required property 'ScaledScoreLogitValue'.: 15
> Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: DomainScore property must have required property 'ScaledScoreLogitStandardError'.: 15
> Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: DomainScore property must have required property 'RawScore'.: 15

Have fixed in source

**Comment by opoudjis** [comment]
10:00 PM, 2022-12-20

~1790~ 1761 errors, ~30728~ 24499 warnings

Errors:
* Property `create/updateObject` is not expected here: https://github.com/nsip/specgen_input_au/issues/50: 960
* Every operation should have security defined on it or on the root level: https://github.com/nsip/specgen_input_au/issues/46: 800
* ~Property `name` is not expected here: https://github.com/nsip/specgen_input_au/issues/45: 25~
* ~Property `in` is not expected here:  https://github.com/nsip/specgen_input_au/issues/45: 2~
* ~Property `host` is not expected here: https://github.com/nsip/specgen_input_au/issues/55: 1~
* ~Property `basePath` is not expected here: https://github.com/nsip/specgen_input_au/issues/55: 1~
* Servers must be present:  https://github.com/nsip/specgen_input_au/issues/55: 1

Warnings:
* Warning Goessner misvalidation: https://github.com/nsip/specgen_input_au/issues/47: ~24806~ 23214

Excluding Goessner examples, which generate a lot of undetected errors

* ~Failing to process alias types: https://github.com/nsip/specgen_input_au/issues/53: 4282~
* Example value must conform to the schema: must match exactly one schema in oneOf: (https://github.com/nsip/specgen_input_au/issues/59): ~642~ 163

Others which are almost all https://github.com/nsip/specgen_input_au/issues/40
 
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `PersonPicture` property must have required property 'Type'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `LearningResource` property must have required property 'ReferenceType'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Activity` property must have required property 'EvaluationType'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property type must be object.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `AggregateStatisticInfo` property must have required property 'Type'.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'EvaluationType'.: 3
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'ReferenceType'.: 3
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must NOT have unevaluated properties {Data Model}.: 4
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: {Data Model} property must NOT have unevaluated properties {Data Model}.: 4
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ActivityTime` property must have required property 'Units'.: 5
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `IdentityAssertions` property must have required property 'SchemaName'.: 5
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `DepartureSchool` property must have required property 'City'.: 5
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'Type'.: 6
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Location` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `PictureSource` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `Duration` property type must be integer.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `CalculationRule` property type must be string.: 8
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'City'.: 10
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `code` property type must be integer.: 13
* Warning XML misvalidation :: : 14
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `PersonRefId` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `OtherLEA` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ParentObjectRefId` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ManagingSchool` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `ResourceRefId` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `InvoicedEntity` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `BilledEntity` property type must be string.: 16
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `LocationRefId` property type must be string.: 32
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `SIF_RefId` property type must be string.: 32
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: must NOT have unevaluated properties {Data Model}.: 34
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `OtherCodeList` property must have required property 'Codeset'.: 50
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'SIF_RefObject'.: 65
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: {Infrastructure} property must NOT have unevaluated properties {Infrastructure}.: 161

**Comment by opoudjis** [comment]
11:30 PM, 2022-12-21

1763 errors, 24119 warnings

The remaining issues are:

Errors:
* Property `create/updateObject` is not expected here: https://github.com/nsip/specgen_input_au/issues/50: 960
* Every operation should have security defined on it or on the root level: https://github.com/nsip/specgen_input_au/issues/46: 800
* Error no-unresolved-refs rule :: Can't resolve $ref:  https://github.com/nsip/specgen_input_au/issues/60: 2
* Servers must be present:  https://github.com/nsip/specgen_input_au/issues/55: 1

Warnings:
* Warning Goessner misvalidation: https://github.com/nsip/specgen_input_au/issues/47: ~23214~ 23234
* Warning XML misvalidation :: https://github.com/nsip/specgen_input_au/issues/56 : 14 
* Example value must conform to the schema: must match exactly one schema in oneOf: (https://github.com/nsip/specgen_input_au/issues/59): ~163~ 489

* Warning info-license rule :: Info object should contain `license` field.: 1
* Warning no-unused-components rule :: Component: "requestPayloads" is never used.: 1
* Warning no-unused-components rule :: Component: "responsePayloads" is never used.: 1
* Warning no-unused-components rule :: Component: "schemaDefinitions" is never used.: 1
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property type must be object.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must NOT have unevaluated properties {Data Model}.: 4 _xml:lang attribute in example object root is being ignored, don't worry about it_
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: {Data Model} property must NOT have unevaluated properties {Data Model}.: 4 _xml:lang attribute in example object root is being ignored, don't worry about it_
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: must NOT have unevaluated properties {Data Model}.: 5 https://github.com/nsip/specgen_input_au/issues/59
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property must have required property 'City'.: 10 _I have already fixed that in source, no idea why it's still showing up_
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `code` property type must be integer.: 13 _Points to validation errors with infrastructure examples_
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property type must be string.: 16 _Points to validation errors with infrastructure examples_, I think
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: {Infrastructure} property must NOT have unevaluated properties {Infrastructure}.: 161 _Points to validation errors with infrastructure examples_
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: must NOT have unevaluated properties {Infrastructure}.: 163 _Points to validation errors with infrastructure examples_

**Comment by opoudjis** [comment]
17:30, 2023-01-16

~1763~ 1760 errors, ~24119~ 24074 warnings

The remaining issues are:

Errors:
* Property `create/updateObject` is not expected here: https://github.com/nsip/specgen_input_au/issues/50: 960
* Every operation should have security defined on it or on the root level: https://github.com/nsip/specgen_input_au/issues/46: 800

Warnings:
* Warning Goessner misvalidation: https://github.com/nsip/specgen_input_au/issues/47: 23234
* Warning XML misvalidation :: https://github.com/nsip/specgen_input_au/issues/56 : 14 
* Example value must conform to the schema: must match exactly one schema in oneOf: (https://github.com/nsip/specgen_input_au/issues/59): 484

* Warning no-unused-components rule :: Component: "requestPayloads" is never used.: 1
* Warning no-unused-components rule :: Component: "responsePayloads" is never used.: 1
* Warning no-unused-components rule :: Component: "schemaDefinitions" is never used.: 1
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property type must be object.: 2
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `code` property type must be integer.: 13 _Points to validation errors with infrastructure examples_
* ~Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property type must be string.: 16~  _Turned out to be another instance of https://github.com/nsip/specgen_input_au/issues/48_
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: {Infrastructure} property must NOT have unevaluated properties {Infrastructure}.: 161 _Points to validation errors with infrastructure examples_
* Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: must NOT have unevaluated properties {Infrastructure}.: 163 _Points to validation errors with infrastructure examples_

**Comment by opoudjis** [comment]
12:30, 2023-01-19

I have segregated OpenAPI 3.0 from OpenAPI 3.1 output, and omitted Goessner and XML examples from the former, in accordance with https://github.com/nsip/specgen_input_au/issues/39

1760 errors, ~24074~ 554 warnings

Same Errors.

Warnings:

Warning no-unused-components rule :: Component: "schemaDefinitions" is never used.: 1
Warning no-unused-components rule :: Component: "responsePayloads" is never used.: 1
Warning no-unused-components rule :: Component: "requestPayloads" is never used.: 1
Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `` property type must be object.: 2
Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: `code` property type must be integer.: 13
Warning XML misvalidation :: : 14
Warning Goessner misvalidation :: : 34
Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: {Infrastructure} property must NOT have unevaluated properties {Infrastructure}.: 161
Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: must NOT have unevaluated properties {Infrastructure}.: 163
Warning no-invalid-media-type-examples rule :: Example value must conform to the schema: must match exactly one schema in oneOf.: 164 (#59)

The remaining XML and Goessner examples are in the SIF infrastructure content, which is currently hard-coded, but which I am about to try to regenerate dynamically, omitting the Goessner/XML references for OpenAPI 3.0.

**Comment by opoudjis** [comment]
19:00, 2023-01-23

1760 errors, ~554~ 3 warnings

Warning no-unused-components rule :: Component: "requestPayloads" is never used.: 1
Warning no-unused-components rule :: Component: "responsePayloads" is never used.: 1
Warning no-unused-components rule :: Component: "schemaDefinitions" is never used.: 1
Error security-defined rule :: Every operation should have security defined on it or on the root level.: 800
Error spec rule :: Property `create/updateObject` is not expected here.: 960



Warning no-unused-components rule :: Component: "requestPayloads" is never used.: 1
Warning no-unused-components rule :: Component: "responsePayloads" is never used.: 1
Warning no-unused-components rule :: Component: "schemaDefinitions" is never used.: 1
Error security-defined rule :: Every operation should have security defined on it or on the root level.: 800
Error spec rule :: Property `create/updateObject` is not expected here.: 960

**Comment by opoudjis** [comment]
18:15, 2023-01-24

````
validating OpenAPI3.0_AU.yaml...
OpenAPI3.0_AU.yaml: validated in 5496ms

Woohoo! Your OpenAPI definition is valid. 🎉
````

Zero errors. Zero warnings.

**Comment by 4pins** [comment]
@opoudjis Wow!
