### ISSUE TITLE
Allow collection objects in top-level enum of objects

### ISSUE THREAD

**Issue by opoudjis** [nsip/specgen_input#59]
The schemas contain lists of just objects:

````
$schema: 'http://json-schema.org/draft-07/schema#'
title: SIF AU v3.5.0
description: JSON Schema derived from SIF AU v3.5.0
type: array
items:
  oneOf:
  - required: [ Activity ]
  - required: [ AddressCollection ]
  - required: [ AggregateCharacteristicInfo ]
  - ...
````

As a result, a payload with `{Activitys ... }` is raising the error:

````
[19292] examples_AU.yaml:2351:9 at #/objectExamples/Activitys/pesc/value

Example value must conform to the schema: must match exactly one schema in oneOf.

2349 |   summary: PESC notation for Activitys
2350 |   value:
2351 |     {"Activitys": {"Activity": [{"RefId" : "C27E1FCF-C163-485F-BEF0-F36F18A0493A", "xml:lang" : "en", "Title" : "Shakespeare Essay - Muc...<859 chars>
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...<859 chars>
````

**Comment by opoudjis** [comment]
have tried fixing this in the obvious place, including renaming SchoolInfoCollection to SchoolInfos; cannot get rid of the error. I will let someone more familiar with OpenAPI look at this.

**Comment by 4pins** [comment]
@opoudjis  Do you know where the duplicate is?  Would it help if I validated a particular JSON Schema for you?

**Comment by opoudjis** [comment]
Thing is, JSON Schema when I run validation against it does *not* complain about this, only Redocly does. I think this is because of the way I've defined the payload: OpenAPI isn't seeing the relevant bit of the schema, even if JSON Schema is.

The salient file is jsonCreate_AU.yaml (or equivalent), which starts as I showed above, and Redocly validating all the example payloads against it. The Goessners all fail of course, and some XMLs do as well now that I've changed how lists are processed to match PESC. But PESC payloads are now failing on containers, and the obvious fix isn't working:

````
$schema: 'http://json-schema.org/draft-07/schema#'
title: SIF AU v3.5.0
description: JSON Schema derived from SIF AU v3.5.0 
type: array
items:
  oneOf:
  - required: [ SchoolInfo ]
  - required: [ SchoolInfos ] <= added
````

plus

````
  SchoolInfo:
    $ref: '#/definitions/SchoolInfo'

  SchoolInfos:
    $ref: '#/definitions/SchoolInfos' <= added
```` 

plus

````
definitions:
  # //////////////////////////////// data object /////////////////////////////
  SchoolInfos:   <= renamed from SchoolInfoCollection
    type: object
    properties:
      SchoolInfo:
        type: array
        items:
          $ref: '#/definitions/SchoolInfo'
  SchoolInfo:
    required:
    - "RefId"
    - "SIF_RefObject"
    - "SchoolName"
    - "SchoolSector"
    type: object
````

The way *to* that schema, in OpenAPI.yaml, is:

````
paths:
  # //////////////////////////////////////////////
  # // SchoolInfos Endpoints 
  # //////////////////////////////////////////////
  /SchoolInfos:
    get:
      responses:
        '200':
          $ref: '#/components/schemas/responsePayloads/createSchoolInfos'
 
...

components:
  schemas:
    responsePayloads:
      createSchoolInfos:
        description: Payload for SchoolInfos
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/schemaDefinitions/createSchemaSchoolInfos'

...

    schemaDefinitions:
      createSchemaSchoolInfo:
        properties:
          SchoolInfo:
            type: object
            description: >-
              Payload definition for SchoolInfo
            $ref: 'jsonSchemaCreate_AU.yaml#/definitions/SchoolInfo'

      createSchemaSchoolInfos:
        properties:
          SchoolInfos:
            type: object
            description: >-
              A Collection of SchoolInfo objects
            properties:
              SchoolInfo:
                type: array
                items:
                    $ref: 'jsonSchemaCreate_AU.yaml#/definitions/SchoolInfo'

````

But Redocly is still complaining that SchoolInfos `must match exactly one schema in oneOf`.

What *does* fix this, I've just discovered, is:

````
      createSchemaSchoolInfos:
        properties:
          SchoolInfos:
            type: object
            description: >-
              A Collection of SchoolInfo objects
            $ref: 'jsonSchemaCreate_AU.yaml#/definitions/SchoolInfos'
````

i.e. not building up the schema for object collections on the fly in the schema definitions, but linking to its separate definition directly as a one liner. Strictly speaking, I don't think what was there was wrong before, but I can see how the alternative is easier to process, even if it isn't wrong. Trying it out.

**Comment by opoudjis** [comment]
No, that won't work, because we're already using -s as a type definition elsewhere, e.g. `LearningResources`. Damn. I will have to restore -Collection.

**Comment by opoudjis** [comment]
That wasn't the issue either. The issue is:

````
      updateSchoolInfos:
        description: Payload for SchoolInfos
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/schemaDefinitions/updateSchemaSchoolInfos'
                  title: SchoolInfos
                - $ref: 'commonDefs-all-headers.yaml#/components/schemas/multipleRequests/deleteMultiSchema'
                  title: deleteRequest

      createSchoolInfosQBE:
        description: Payload for Multiple POST request for SchoolInfos
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/schemaDefinitions/createSchemaSchoolInfos'
                  title: SchoolInfos
                - $ref: 'commonDefs-all-headers.yaml#/components/schemas/multipleResponses/createMultiSchema'
                  title: createRequest
````

The very same payload, validated against

````
      createSchoolInfos:
        description: Payload for SchoolInfos
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/schemaDefinitions/createSchemaSchoolInfos'
````

is validated without incident. 

As it turns out, if I validate against:

````
      updateSchoolInfos:
        description: Payload for SchoolInfos
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/schemaDefinitions/updateSchemaSchoolInfos'
                  title: SchoolInfos
````

I still get that error, but if I validate against:

````
      updateSchoolInfos:
        description: Payload for SchoolInfos
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/schemaDefinitions/updateSchemaSchoolInfos'
````

I do not.

My conclusion in light of that is that this is a Redocly error: oneOf is not passing schemas correctly for validation, for whatever reason. If this turns out to be a real error for OpenAPI, I will need to revisit it, but for now, I will leave this be.

**Comment by opoudjis** [comment]
The newly arising error

`Example validation errored: type value must be ["string","array"].`

appears to also be associated with OneOf validation: in particular, the following annotation (which I had not eliminated) is not being recognised as valid OpenAPI 3.0:

````
            schema:
              oneOf:
                - $ref: '#/components/schemas/schemaDefinitions/updateSchemaSchoolInfos'
                  title: SchoolInfos
                - $ref: 'commonDefs-OpenAPI3.0-all-headers.yaml#/components/schemas/multipleRequests/deleteMultiSchema'
                  title: deleteRequest
````

What is worrying is, the validator seems to be complaining about this under OpenAPI 3.1 as well. It is impossible to work out from the RFC whether this is truly illegal—OneOf alternates between schemas, and schemas should be able to be annotated with "title". For 3.0 though, this has to go.

**Comment by opoudjis** [comment]
No, that was not the issue:

````
Example validation errored: type value must be ["string","array"].

74424 | application/json:
74425 |   schema:
74426 |     oneOf:
      |     ^^^^^^
74427 |       - $ref: '#/components/schemas/schemaDefinitions/createSchemaCollectionDeclarations'
      |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
74428 |       - $ref: 'commonDefs-OpenAPI3.0-all-headers.yaml#/components/schemas/multipleResponses/createMultiSchema'
      |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
````

**Comment by opoudjis** [comment]
With the examples debugged to be valid PESC JSON, the `must match exactly one schema in oneOf` error has now gone away in Open3.0 (though not in Open3.1, where it still is being triggered by XML, it seems).

**Comment by opoudjis** [comment]
This is the culprit of the new "type value must be ["string","array"]." error

````
  update:
    type: object
    properties:
...
      error:
        type:
        $ref: '#/definitions/error'
````

This is what is being generated from the Infrastructure specgen XML; the type of the error is not being populated. Will require XSLT debugging to deal with novel eventuality.

**Comment by opoudjis** [comment]
This is because of an erroneous specification in the Infrastructure specgen

To see this live at work, go to

http://specification.sifassociation.org/Implementation/Infrastructure/3.5/CommonTypes.html#ErrorType

Click on the definition of "errorType", which takes you to its definition:

http://specification.sifassociation.org/Implementation/Infrastructure/3.5/CommonTypes.html#ErrorType

corresponding to the specgen XML

`<Type ref="CommonTypes" name="errorType"/>`

... You don't go anywhere. Because ErrorType is not defined as a type at all. It is exclusively defined as an object.

This kind of informal laxity has been allowed in specgen, and it only has surfaced in the AU spec as we started automatic first XML and then JSON mappings out of specgen XML. It is a blight that this has not been fixed to date, and from the AU experience, the fixes may well need to be substantial in both NA and IN.

In any case, the solution here is to define the error object as an instance of the error type, as is done in the AU spec between LearningResourcePackage and AbstractContentElement. I am going to branch specgen_input_infra for that fix. Without that fix though, there simply is no definition of error as an element of other payloads, that OpenAPI (or indeed specgen rendering!) can access.

**Comment by opoudjis** [comment]
Specgen is in fact able to resolve the references to errorType from the common types, to the object definition. So specgen does not have   a problem here...

... but the downstream processors clearly do, and rather than go hunting, I'm just going to rename errorType into errorCommonType, to avoid confusion. (The surfaced element name of course remains "error", this is an invisible change.)

**Comment by opoudjis** [comment]
There are no further validation errors in 3.0 with infrastructure
