### ISSUE TITLE
LearningStandardDoc and LearningStandardItem not Venetian Blind

### ISSUE THREAD

**Issue by vinceparedes** [nsip/specgen_input#7]
_From @vinceparedes on December 4, 2017 11:39_

Scrolling through the html I noticed LearningStandardDocument has CopyRight as a complex element. LearningStandardItem looks untouched. You may already know this. 

_Copied from original issue: nsip/specgen#35_

**Comment by LindaNSIP** [comment]
Done in 3.4.3
